FROM node:20-alpine as build
WORKDIR /app
COPY package.json ./
RUN rm -f package-lock.json
RUN npm cache clean --force
RUN npm install
COPY . .
ENV VITE_API_URL=/api
ARG VITE_GOOGLE_CLIENT_ID
ENV VITE_GOOGLE_CLIENT_ID=$VITE_GOOGLE_CLIENT_ID
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
