services:
  db:
    image: postgres:15-alpine
    container_name: openlib-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - openlib-net
  api:
    build: ./server
    container_name: openlib-api
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:${DB_PASSWORD}@db:5432/openlib
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GMAIL_USER: ${GMAIL_USER}
      GMAIL_CLIENT_ID: ${GMAIL_CLIENT_ID}
      GMAIL_CLIENT_SECRET: ${GMAIL_CLIENT_SECRET}
      GMAIL_REFRESH_TOKEN: ${GMAIL_REFRESH_TOKEN}
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - openlib-net
  web:
    build:
      context: ./client
      args:
        - VITE_GOOGLE_CLIENT_ID=${VITE_GOOGLE_CLIENT_ID}
    container_name: openlib-web
    restart: always
    ports:
      - "8080:80"
    networks:
      - openlib-net
volumes:
  postgres_data:
networks:
  openlib-net:
    driver: bridge
